config/routes.rb
Landingpage::Application.routes.draw do
  resources :feed_items do
    resources :comments
  end

  devise_for :users
  
  authenticated :user do
    # root :to => "feed#index" #timeline
    root :to => "feed#timeline"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/registrations#new"
    end
  end

  get "welcome", to: redirect("/users/sign_in")
  get "logout" => "page#logout"

  #first time log in
  get "users/:id/first_login" => "feed#user_first_login", as: "user_first_login"

  get "users/:id/feeds" => "feed#user_news_feed", as: "user_news_feed"
  post "users/readlists" => "feed#user_readlist_create"
  get "users/readlists" => "feed#user_readlists", as: "user_readlists"
  get "users/:user_token/readlists" => "feed#user_readlists"
  get "users/readlist/:token" => "feed#user_readlist_read", as: "user_readlist_read"
  get "users/:user_token/following_profiles" => "feed#user_following_profiles"
  delete "users/readlist/:token" => "feed#user_readlist_delete", as: "user_readlist_delete"
  post "readlist/:token/privacy" => "feed#user_readlist_is_public", as: "user_readlist_is_public"

  # Author Routes
  get "timeline" => "feed#timeline", as: "timeline"
  get "authors" => "feed#author_list", as: "author_list"
  get "recommendedauthors" => "feed#author_recommendation", as: "author_recommendation"
  get "authors/:author_token" => "feed#author_show_posts", as: "author_show_posts"
  get "search/authors" => "feed#author_search", as: "search_author"
  post "authors/:token/follow" => "feed#author_follow", as: "author_follow"

  
   
  post "subscribe" => "page#homepage_subscribe"
  get "survey/2" => "page#survey_2"
  get "admin/subscriptions" => "page#admin_subscriptions"


  get "admin/authors" => "profile#index"
  get "admin/posts" => "profile#admin_posts"
  post "admin/authors" => "profile#create"
  put "admin/authors/:token" => "profile#update"
  get "admin/authors/:token" => "profile#show", as: "admin_author_show"
  delete "admin/authors/:token" => "profile#delete"
  delete "admin/authors/:token/feed/:feed_token" => "profile#dissociate_feed"
  post "admin/authors/feeds/:author_token" => "profile#feed_update"

  get "admin/feeds" => "admins/feeds#feed"

  get "admin/authorsearchlist" => "profile#author_search_list"
  get "page/page2"


  get "post/:token" => "feed#post_view", as: 'post_view'

  get "post/1/:token" => "feed#post_view1"
  get "post/2/:token" => "feed#post_view2"
  get "post/3/:token" => "feed#post_view3"
  get "post/4/:token" => "feed#post_view4"
  get "post/5/:token" => "feed#post_view5", as: "post_view5"
  get "post/6/:token" => "feed#post_view6"

  post "like" => "likes#toggle"
  get "likes/:type/:type_token" => "likes#index"

  # get "/feed_items/:feed_item_id/comments" => "comments#index", as: "feed_item_comments"
  # post "/feed_items/:feed_item_id/comments" => "comments#create"
end

app/models/feed.rb
class Feed
  include Mongoid::Document
  include Mongoid::Token
  include Mongoid::Timestamps

  field :title, type: String
  field :url, type: String
  field :feed_url, type: String
  field :etag, type: String
  field :last_modified, type: Time
  field :create_date, type: Time # Time of creation
  field :update_date, type: Time # Time of update
  field :feed_class, type: String # Rss / Atom
  field :feed_item_class, type: String # RssItem / AtomItem

  field :feed_item_tags, type: Array
  field :flags, type: Hash #eg flags.disabled
  field :feed_item_parsers, type: Array #An ordered list of specific Parsers
  field :tags, type: Array
  token

  def feedzirra_object
    return @feedzirra_object
  end

  def self.create_by_feed_url(feed_url)
    self.find_by(feed_url: feed_url) or self.create(feed_url: feed_url)
  end

  def pull
    @feedzirra_object = nil
    if self.feed_class.blank? || (self.etag.blank? && self.last_modified.blank?)
      @feedzirra_object = Feedzirra::Feed.fetch_and_parse(feed_url)
      if @feedzirra_object == 0
        return nil
      end

      save_feed @feedzirra_object

      logger.debug("FeedCrawl - FetchAndParse: Found #{@feedzirra_object.entries.count} new items")
      @feedzirra_object.entries.each do |feed_item|
        feed_item_obj = save_feed_items feed_item
        if feed_item.content.blank?
          Resque.enqueue(FeedItemIndetailExtractor, feed_item_obj.token)
        end
        process_parsers feed_item_obj
      end
    else
      @feedzirra_object = self.feed_class.constantize.new
      @feedzirra_object.feed_url = self.feed_url
      @feedzirra_object.etag = self.etag
      @feedzirra_object.last_modified = self.last_modified

      last_feed_item = self.feed_item_class.constantize.new
      last_feed_item.url = FeedItem.where(feed_token: self.token).sort(published: -1).first.url

      @feedzirra_object.entries = [last_feed_item]
      updated_feeds = Feedzirra::Feed.update(@feedzirra_object)
      @feedzirra_object = updated_feeds
      logger.debug("FeedCrawl - Update: Found #{@feedzirra_object.new_entries.count} new items")
      @feedzirra_object.updated? and @feedzirra_object.new_entries.each do |feed_item|
        feed_item_obj = save_feed_items feed_item
        if feed_item.content.blank?
          Resque.enqueue(FeedItemIndetailExtractor, feed_item_obj.token)
        end
        process_parsers feed_item_obj
      end
    end
    true
  end

  def save_feed(feed)
    self.title = feed.title
    self.url = feed.url
    self.feed_url = feed.feed_url
    self.etag = feed.etag
    self.last_modified = feed.last_modified
    self.feed_class = feed.class.to_s
    if feed.entries.count > 0
      self.feed_item_class = feed.entries.first.class.to_s
    end
    save
  end

  def save_feed_items(feed_item)
    # Use url to check if something has been added
    feedItem = FeedItem.find_by({url: feed_item.url})
    if feedItem
      feedItem
    else
      feedItem = FeedItem.create({
        title: feed_item.title,
        url: feed_item.url,
        author: feed_item.author,
        summary: feed_item.summary,
        content: feed_item.content,
        published: feed_item.published,
        entry_id: feed_item.entry_id,
        # categories: feed_item.categories,
        feed_token: self.token,
        tags: self.feed_item_tags
      })
    end
  end

  def process_parsers(feed_item)
    puts "Flags: #{flags}"
    if flags and not flags["dynamic_author"].blank?
      p = FeedParser::DynamicAuthorParser.new
      p.process(feed_item, self)
    end

    if flags and not flags["insead"].blank?
      p = FeedParser::InseadParser.new
      p.process(feed_item, self)
    end
  end
end

app/controllers/admins/feeds_controller.rb
class Admins::FeedsController < ApplicationController
  def feed
    if params[:q]
      @feeds = Feed.where(feed_url: /#{params[:q]}/i).limit(50)
    else
      @feeds = []
    end
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController  

  def author_list
    authenticate_user!
    @orgs = {
      'standford-news-insights' => 'Stanford',
      'insead-blog' => 'INSEAD',
      'havard-business-school' => 'Havard',
      'dartmouth-newsroom' => 'Dartmouth',
      'columbia-global-insights' => 'Chicago',
      'kellog-blogs' => 'Kellog',
      'imd-tomorrows-challenges' => 'IMD',
    }
    # @profiles = Profile.where("token" => {"$in"=> current_user.following_profiles})
    @disable_search_nav = true
    if request.xhr?
      page = params[:page] ? params[:page] : 1
      org = params[:org]
      if org
        @profiles = Profile.where("tags" => org).order_by(:name => 1).page(page)
        render template: "feed/author_list.json", content_type: "application/json"
      else
        @profiles = Profile.order_by(:name => 1).page(page)
        render template: "feed/author_list.json", content_type: "application/json"
      end
    end
  end

  def author_show_posts
    authenticate_user!
    
    paginate_page = (params[:page].blank?) ? 0 : params[:page]

    @author_token = params[:author_token]

    current_user.following_profiles ||= []
    @following_authors = Profile.where("token" => {"$in"=> current_user.following_profiles})
    @author = Profile.find(@author_token);
    @author.feed_tokens ||= []
    
    @feed_items = FeedItem.or({"feed_token" => {"$in" => @author.feed_tokens}}, {"profile_tokens" => @author.token}).
      order_by("published desc").page(paginate_page)
    @paginate_count = FeedItem.or({"feed_token" => {"$in" => @author.feed_tokens}}, {"profile_tokens" => @author.token}).count
  end

  def author_search
    search_condition =  params[:search]
    if not search_condition.blank?    
      @author_search_result = Profile.author_search(search_condition,current_user.email)
    end
    @disable_search_nav = true
  end

  def author_follow
    # authenticate_user!
    # if request.xhr?
      # @todo check valid user
      token = params[:token]
      # unless Profile.find(token)
      #   return render json: {status: "error", message: "Invalid token."}
      # end

      added = true

      current_user.following_profiles ||= []
      if current_user.following_profiles.include?(token)
        current_user.following_profiles.delete token
        added = false
      else
        current_user.following_profiles << token
      end
      current_user.save

      if added
        render json: { status: "ok", message: "following user", value: added }
      else
        render json: { status: "ok", message: "unfollowing user", value: added }
      end
  end


  def user_news_feed
    authenticate_user!
    
    if current_user.first_time
      return redirect_to author_list_path    
    end   

    # pagination components
    default_limit = 20
    default_page = 1
    paginate_limit = (params[:limit].blank?) ? default_limit : params[:limit]
    paginate_page = (params[:page].blank?) ? default_page : params[:page]    
      
    @following_authors = Profile.where("token" => {"$in"=> current_user.following_profiles})
    feed_tokens = []
    
    @following_authors.each do |following_author|
      feed_tokens += following_author.feed_tokens  if following_author.feed_tokens.kind_of?(Array)
    end   

    @feed_items = FeedItem.where("feed_token" => {"$in" => feed_tokens}).
        order_by("published desc").page(paginate_page)

    @paginate_count = FeedItem.where("feed_token" => {"$in" => feed_tokens}).count
  end

  def post_view
    authenticate_user!
    token = params[:token]
    @feed_item = FeedItem.find(token)
    not_found unless @feed_item
    
    if @feed_item
      user_token = 'anonymous'
      user_token = current_user.token if user_signed_in?
      ModelViewLog.create(type: 'feed_item', type_token: @feed_item.token, user_token: user_token)
      @feed_item.update_attributes(view_count: @feed_item.view_count + 1)
    end

    @author = Profile.find_by("feed_tokens" => @feed_item.feed_token) 
    unless @author
      @author = Profile.find(@feed_item.profile_tokens[0])
    end

    @model = @feed_item
    @comment = Comment.new
    @comment.author = current_user.token
  end

  def post_view1
    token = params[:token]
    @feed_item = FeedItem.find(token)
  end

  def post_view2
    token = params[:token]
    @feed_item = FeedItem.find(token)
  end
  def post_view3
    token = params[:token]
    @feed_item = FeedItem.find(token)
    render layout: "signup"
  end
  def post_view4
    token = params[:token]
    @feed_item = FeedItem.find(token)
    render layout: "signup"
  end
  def post_view5
    authenticate_user!
    @profiles = Profile.all.sort({:score => -1}).limit(3)
    @feed_items = FeedItem.all.paginate(limit: 25)

    @search_condition =  params[:search]
    if not @search_condition.blank?    
      @author_search_result = Profile.author_search(@search_condition,current_user.email)
    end
  end

  def author_recommendation
    authenticate_user!
    recommend_author = Profile.new
    @profiles = recommend_author.author_recommend(current_user.token)
    @disable_search_nav = true
  end

  def index
    authenticate_user!
    # return redirect_to user_news_feed_path(current_user.token)
    return redirect_to timeline_path
  end

  # GET /timeline
  def timeline
    authenticate_user!
    if request.xhr?
      page = params[:page] ? params[:page] : 1
      @feed_items = FeedItem.order_by(published: -1).page(page)
      return render template: "feed/timeline.json", content_type: "application/json"
    end
  end

  # POST /users/readlist
  def user_readlist_create
    authenticate_user!

    readlist_name = params[:title]
    if readlist_name.blank?
      return render json: {status: "error", message: "Readlist cannot be empty"}
    end
    
    profile_token = params[:profile_token]
    profile = Profile.find(profile_token)
    if profile.blank?
      return render json: {status: "error", message: "Profile not found"}
    end

    current_user.following_profiles ||= []
    if not current_user.following_profile? profile.token
      current_user.following_profiles << profile_token unless current_user.following_profile?(profile.token)
      current_user.save
    end

    current_user.readlist_tokens ||= []
    readlist = Readlist.find_by(title: readlist_name, token: {"$in" => current_user.readlist_tokens}) 
    unless readlist
      readlist = Readlist.create(title: readlist_name, profile_tokens: [profile_token])      
      current_user.readlist_tokens << readlist.token
      current_user.save
      return render json: {status: "ok", message: "Readlist created and Author added to Readlist", action: "add"}
    end

    readlist.profile_tokens ||= []
    if readlist.profile_tokens.include? profile_token
      readlist.profile_tokens.delete profile_token
      readlist.save
      return render json: {status: "ok", message: "Author removed from existing Readlist", action: "delete"}
    else
      readlist.profile_tokens << profile_token
      readlist.save
      return render json: {status: "ok", message: "Author added to existing Readlist", action: "add"}
    end
  end

  # DELETE /users/readlist/:token
  def user_readlist_delete
    authenticate_user!
    readlist = Readlist.find(params[:token])
    if current_user.readlist_tokens.include?params[:token]
      readlist.destroy
      current_user.readlist_tokens.delete params[:token]
      current_user.save
    end
    return redirect_to user_readlists_path
  end

  # Make readlist public or private /users/read

  def user_readlist_is_public
    authenticate_user!
    readlist = Readlist.find(params[:token])
    if current_user.readlist_tokens.include?params[:token]
      if readlist.is_public
        readlist.update(:is_public => false)
        is_public = false
        return render json: {status: "ok", message: "Readlist made private", value: is_public }
        #current_user.readlist_tokens.update(:is_public =>false) params[:token]
        
      else
        readlist.update(:is_public => true)
        is_public = true
        #current_user.readlist_tokens.update(:is_public =>true) params[:token]
         return render json: {status: "ok", message: "Readlist made public", value: is_public}
      end
      current_user.save
    end
    return redirect_to user_readlists_path
  end

  # GET /users/readlist
  # GET /users/:user_token/readlists
  def user_readlists
    authenticate_user!
    if request.xhr?
      readlists = {}
      current_user.my_readlists.each do |readlist|
        readlists[readlist.token] = readlist.as_json(except: "_id")
      end
      return render :json => { readlists: readlists }
    else
    end
  end

  # GET /user/readlist/:token
  def user_readlist_read
    authenticate_user!
    @readlist = Readlist.find(params[:token])
    @readlist.profile_tokens ||= []
    feed_tokens = []
    @readlist_authors = Profile.where(token: {"$in" => @readlist.profile_tokens})
      # .order_by("name")
    @readlist_authors.each do |profile|
      feed_tokens += profile.feed_tokens unless profile.feed_tokens.blank?
    end

    params[:per_page] ||= 20
    @feed_items = FeedItem.or({:feed_token.in => feed_tokens}, {:profile_tokens.in => @readlist.profile_tokens})
      .order_by("published desc")
      .page(params[:page])

    current_user.following_profiles ||= []
    @following_authors = Profile.where(token: {"$in" => current_user.following_profiles})
  end

  # GET /users/:user_token/following_profiles
  def user_following_profiles
    authenticate_user!
    if current_user.token != params[:user_token]
      # @todo check for permission to access other profiles
      # user = User.find(params[:user_token])
      return render json: {status: "error", message: "Access denied"}
    end
    
    if request.xhr?
      following_profiles = {}
      current_user.my_following_profiles.each do |p|
        following_profiles[p.token] = p.as_json(only: [:name, :token])
      end

app/helpers/feed_helper.rb
module FeedHelper
end

app/views/feed/_author_list_organization_header.html.slim
= link_to "All", "/authors"
- Organization.org_name_tag_map.each do |org_url, org|
  button.btn.btn-xs.btn-link.spaced-at-right class="#{ (params[:org] == org_url ? 'active':'')}"
    = link_to org, "/authors?org=#{org_url}"
- if params[:search]
  button.btn.btn-xs.btn-link.spaced-at-right class="active" Search

app/views/feed/_new_readlist_modal.html.slim
#new-readlist-modal.modal class="{{modal_status}}"
  form.modal-dialog ng-submit="saveReadlist()"
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button" &times;
        h4.modal-title Name of the Read List
      .modal-body
        input.form-control ng-model="readlist_name" placeholder="Read List Name"
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button" Cancel
        input.btn.btn-primary.btn-save type="submit" value="Save"

app/views/feed/author_list.html.slim
.authorlist ng-controller="FeedAuthorListCtrl" ng-init="init()"

  .row
    .col-sm-3.hidden-xs
      = render partial: "user_read_links"
  
    .col-sm-8.col-xs-12

      - if current_user.first_time
        .alert.alert-dismissable.alert-info.alert-message
          button.close area-hidden="true" data-dismiss="alert" type="button" onclick="$('.alert').fadeOut()"× 
          p 
            strong Thank you for joining Snippr! 
          br
          p Please click "Follow" to get updates in your timeline from the professors
          - current_user.first_time = false
          - current_user.save
      h2 Please click on follow to get updates from the professors 
      .dark-line
      .univerity-buttons.col-sm-offset-3.col-sm-9
      button.btn.btn-xs.btn-link.spaced-at-right
        = render partial: "author_list_organization_header"
        
        .light-line
      .search-author.pull-right.col-sm-offset-5.col-sm-7.pull-left
        = render partial: "layouts/user_search"

      .clearfix

      div infinite-scroll="authorlist.nextPage()" infinite-scroll-disabled='authorlist.busy' infinite-scroll-distance="1"
        .row.author-container ng-repeat="author in authorlist.authors"
          .col-sm-11.col-xs-12
            .col-sm-3.col-xs-3
              img.img-circle.thumbnail.author-thumbnail.pull-right ng-src="{{author.photo_url_fixed}}"
            .col-sm-9.col-xs-9
              h2.author-post
                a href="/authors/{{author.token}}" {{ author.name }}
              p() {{author.short_description}}

              followbutton.btn-xs.btn> target="getProfile(author.token)"

              readlistbutton> target="getProfile(author.token)" readlists-model="my_readlists" after="init()"
                a.btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
                  ' Add to Readlist
                  span.caret
              
              hr
    = render partial: "new_readlist_modal"

app/views/feed/author_list.json.erb
<%
p = @profiles.map do |p|
  profile = p.as_json
  profile[:photo_url_fixed] = p.photo_url_fixed
  profile
end
%>
<%= p.to_json.html_safe %>

app/views/feed/author_recommendation.html.slim
.authorlist ng-controller="FeedAuthorListCtrl" ng-init="init()"
  
  .row
    .col-sm-3.hidden-xs
      = render partial: "user_read_links"
  
    .col-sm-8  
      h2 Recommended Authors
      .dark-line
              
      .search-author.pull-right.col-sm-offset-5.col-sm-7
        = render partial: "layouts/user_search"
      .clearfix


      - @profiles.each do |profile|
        .row.author-container
          .col-sm-11.col-xs-12
            .col-sm-3.col-xs-3
              img.img-circle.thumbnail.author-thumbnail.pull-right ng-src="#{profile.photo_url}"
            .col-sm-9.col-xs-9
              h2.author-post
                a href="/authors/#{profile.token}" #{profile.name}
              p #{profile.short_description}

              followbutton.btn-xs.btn> target="getProfile('#{profile.token}')"

              readlistbutton> target="getProfile('#{profile.token}')" readlists-model="my_readlists" after="init()"
                a.btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
                  ' Add to Readlist
                  span.caret

              hr

    = render partial: "new_readlist_modal"

app/views/feed/author_search.html.slim
.authorlist ng-controller="FeedAuthorListCtrl" ng-init="init()"
  .row
    .col-sm-3.hidden-xs
      = render partial: "user_read_links"
  
    .col-sm-8    
      h2 Search Results
      .dark-line

      button.btn.btn-xs.btn-link.spaced-at-right
        = render partial: "author_list_organization_header"
        .light-line

      .search-author.pull-right.col-sm-offset-5.col-sm-7
        = render partial: "layouts/user_search"
      .clearfix

      - if not @author_search_result.blank?
        - @author_search_result.each do |profile|
          .row.author-container
            .col-sm-11.col-xs-12
              .col-sm-3.col-xs-3
                img.img-circle.thumbnail.author-thumbnail.pull-right ng-src="#{profile.photo_url_fixed}"
              .col-sm-9.col-xs-9
                h2.author-post
                  a href="/authors/#{profile.token}" #{profile.name}
                p #{profile.short_description}

                followbutton.btn-xs.btn> target="getProfile('#{profile.token}')"

                readlistbutton> target="getProfile('#{profile.token}')" readlists-model="my_readlists" after="init()"
                  a.btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
                    ' Add to Readlist
                    span.caret
                hr

      - else
        .col-sm-11
          h2.author-post
            = "author not found"
          p
            a.text-primary href="/authors" Go to the list of authors
   

    = render partial: "new_readlist_modal"

app/views/feed/author_show_posts.html.slim
.authorpost.container ng-controller="FeedAuthorShowPostsCtrl" ng-init="init()"
  
  .row
    .col-sm-3.col-xs-3
      img.img-circle.author-thumbnail.thumbnail.pull-right ng-src="#{@author.photo_url_fixed}"
      

    .col-sm-6.col-xs-9
      h2.author-post
        = @author.name
        - unless @author.twitter_handle.blank?
          span.text-info.twitter-author 
            = link_to "@%s" % @author.twitter_handle, "https://twitter.com/%s" % @author.twitter_handle, target: "_blank"
      p #{ @author.short_description }
      p 
        | Associated with: 
        u
          - if not @author.tags.blank?
            = Organization.name_for @author.tags[0]
      p
        span.spaced-at-right() #{@paginate_count} posts.
        / | 100 views
        / span 24 followers

      -# FOLLOW BUTTON
      followbutton.btn-xs.btn> target="getProfile('#{@author.token}')"

      readlistbutton target="getProfile('#{@author.token}')" readlists-model="my_readlists" after="init()"
        a.btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
          ' Add to Readlist
          span.caret

      hr.dark-line

  .row 
    .col-sm-3.hidden-xs
      = render partial: "user_read_links"

    .col-sm-8   
      / .pull-right.text-muted
      /   = will_paginate @feed_items
      .clearfix
  
      - @feed_items.each do |feed_item|
        h2.post-title
          a> href="/post/#{feed_item.token}" #{raw feed_item.title }
          / a href="{{ post.url }}" Go

        / .author-view-page
        /   hr
        /     strong          
        /       = link_to URI(feed_item.url).host, feed_item.url, target: "_blank", class: "text-primary"
        
        .post-content 
          div
            = feed_summary feed_item.summary
        br
        - if not feed_item.published.blank?
          p.text-muted.dateline.pull-left.spaced-at-right id="#{feed_item.token}" Posted #{time_ago_in_words feed_item.published} ago 
          .text-muted.dateline
            | #{feed_item.view_count} Views | #{feed_item.comments_list.count} Comments | #{feed_item.like_count} Likes
        / .social.pull-right.clearfix.text-info.spaced-at-top
        /   span.social-buttons
        /     i.icon-heart-empty
        /   span.social-buttons
        /     i.icon-facebook-sign
        /   span.social-buttons
        /     i.icon-twitter-sign
        /   span.social-buttons
        /     i.icon-linkedin-sign 

        .clearfix
        hr
      / .pull-right.text-muted
      /   = will_paginate @feed_items
   


  = render partial: "new_readlist_modal"

app/views/feed/post_view3.html.slim
<div id="carousel-example-generic" class="carousel slide">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="..." alt="...">
      <div class="carousel-caption">
        ...
      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="icon-next"></span>
  </a>
</div>

app/views/feed/user_readlist.html.slim
.readlist  
  h2 All Readlists
  p.go-to-feed
    a href="#" Create new 
  .row
    .col-md-12
      .dark-line
  .row
    .col-md-12
      .col-md-offset-8.col-md-4
        form.form-inline ng-submit="search()"
          .form-group>
            input.form-control type="text" ng-model="search_q" placeholder="Enter readlist"
          .form-group>
            input.form-control.btn-primary type="submit" value="Search"
  .row 
    .col-md-12 
      .col-md-8
        h2
          - if current_user.my_readlist.blank?
            h2 You have no readlists
          - else
            ul.fix-list
              h2
                - current_user.my_readlist.each do |readlist|
                  li
                    = link_to readlist.title, user_readlist_read_path(token: readlist.token)

                  p
                  button.btn.btn-danger.btn-xs.spaced-at-right Delete readlist
                  button.btn.btn-default.btn-xs Add authors
                  hr

app/views/feed/user_readlist_read.html.slim
div.container ng-controller="FeedAuthorShowPostsCtrl" ng-init="init()"

  .row 
    .col-sm-3.hidden-xs
      = render partial: "user_read_links"

    .col-sm-8.col-xs-12

      h2
        a href="#" #{@readlist.title}
      ul.author-in-readlist.hidden-xs
        - @readlist_authors.each do |profile|
          li.text-muted>
            =' link_to profile.name, author_show_posts_path(author_token: profile.token), class: "spaced-at-right"
      .clearfix
      .dark-line

      .clearfix

      - @feed_items.each do |feed_item|
        h2.author-feed
          - @readlist_authors.each do |readlist_author|
            - if feed_item.profile_tokens.include? readlist_author.token or readlist_author.feed_tokens.include?(feed_item.feed_token) 
              a href="/authors/#{readlist_author.token}" #{{readlist_author.name}}               

              / readlistbutton> target="getProfile('#{readlist_author.token}')" readlists-model="my_readlists" after="init()"
              /   a.btn.btn-xs.dropdown-toggle data-toggle="dropdown"
              /     i.icon-plus-sign

        .clearfix

        - if feed_item.published
          p.text-muted.dateline() #{ time_ago_in_words feed_item.published } ago
        h2.post-title
          a> href="/post/#{feed_item.token}" #{ feed_item.title }
          / a href="{{ post.url }}" Go

        .post-content #{feed_summary feed_item.summary}
        / .social.pull-right.clearfix.text-info.spaced-at-top
          / span.social-buttons
          /   i.icon-heart-empty
          / span.social-buttons
          /   i.icon-facebook-sign
          / span.social-buttons
          /   i.icon-twitter-sign
          / span.social-buttons
          /   i.icon-linkedin-sign 

        .clearfix
        hr


  = render partial: "new_readlist_modal"