config/routes.rb
Landingpage::Application.routes.draw do
  resources :feed_items do
    resources :comments
  end

  devise_for :users
  
  authenticated :user do
    # root :to => "feed#index" #timeline
    root :to => "feed#timeline"
  end
  unauthenticated :user do
    devise_scope :user do 
      get "/" => "devise/registrations#new"
    end
  end

  get "welcome", to: redirect("/users/sign_in")
  get "logout" => "page#logout"

  #first time log in
  get "users/:id/first_login" => "feed#user_first_login", as: "user_first_login"

  get "users/:id/feeds" => "feed#user_news_feed", as: "user_news_feed"
  post "users/readlists" => "feed#user_readlist_create"
  get "users/readlists" => "feed#user_readlists", as: "user_readlists"
  get "users/:user_token/readlists" => "feed#user_readlists"
  get "users/readlist/:token" => "feed#user_readlist_read", as: "user_readlist_read"
  get "users/:user_token/following_profiles" => "feed#user_following_profiles"
  delete "users/readlist/:token" => "feed#user_readlist_delete", as: "user_readlist_delete"
  post "readlist/:token/privacy" => "feed#user_readlist_is_public", as: "user_readlist_is_public"

  # Author Routes
  get "timeline" => "feed#timeline", as: "timeline"
  get "authors" => "feed#author_list", as: "author_list"
  get "recommendedauthors" => "feed#author_recommendation", as: "author_recommendation"
  get "authors/:author_token" => "feed#author_show_posts", as: "author_show_posts"
  get "search/authors" => "feed#author_search", as: "search_author"
  post "authors/:token/follow" => "feed#author_follow", as: "author_follow"

  
   
  post "subscribe" => "page#homepage_subscribe"
  get "survey/2" => "page#survey_2"
  get "admin/subscriptions" => "page#admin_subscriptions"


  get "admin/authors" => "profile#index"
  get "admin/posts" => "profile#admin_posts"
  post "admin/authors" => "profile#create"
  put "admin/authors/:token" => "profile#update"
  get "admin/authors/:token" => "profile#show", as: "admin_author_show"
  delete "admin/authors/:token" => "profile#delete"
  delete "admin/authors/:token/feed/:feed_token" => "profile#dissociate_feed"
  post "admin/authors/feeds/:author_token" => "profile#feed_update"

  get "admin/feeds" => "admins/feeds#feed"

  get "admin/authorsearchlist" => "profile#author_search_list"
  get "page/page2"


  get "post/:token" => "feed#post_view", as: 'post_view'

  get "post/1/:token" => "feed#post_view1"
  get "post/2/:token" => "feed#post_view2"
  get "post/3/:token" => "feed#post_view3"
  get "post/4/:token" => "feed#post_view4"
  get "post/5/:token" => "feed#post_view5", as: "post_view5"
  get "post/6/:token" => "feed#post_view6"

  post "like" => "likes#toggle"
  get "likes/:type/:type_token" => "likes#index"

  # get "/feed_items/:feed_item_id/comments" => "comments#index", as: "feed_item_comments"
  # post "/feed_items/:feed_item_id/comments" => "comments#create"
end

app/views/layouts/_alerts.html.slim
- if notice and notice.length > 0
	.alert.alert-success.alert-dismissable
 		button.close aria-hidden="true" data-dismiss="alert" type="button"
		= notice

- if alert
	.alert.alert-warning.alert-dismissable
 		button.close aria-hidden="true" data-dismiss="alert" type="button"
		= alert

app/views/layouts/_js_tracking_links.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43905365-1', 'snippr.co');
  ga('send', 'pageview');

javascript:
  var _kmk = _kmk || '8731335d908493cd0d58b99229da5ad7965bf38c';
  function _kms(u){
    setTimeout(function(){
      var d = document, f = d.getElementsByTagName('script')[0],
      s = d.createElement('script');
      s.type = 'text/javascript'; s.async = true; s.src = u;
      f.parentNode.insertBefore(s, f);
    }, 1);
  }
  _kms('//i.kissmetrics.com/i.js');
  _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
= csrf_meta_tags
= javascript_tag "var AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery?

app/views/layouts/_user_account_nav.html.slim
.nav.navbar-nav.btn-group.username
  - if user_signed_in?
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        = current_user.display_name
        b.caret
      ul.dropdown-menu
        li
          = link_to "My Profile"
        li
          = link_to "Logout", destroy_user_session_path, method: "delete"
  - else
    li.dropdown
      = link_to "Sign in", new_user_session_path
.clearfix

app/views/layouts/_user_search.html.slim
.search-box.navbar-form
	= form_tag search_author_path, :method => 'get' do 

		.col-xs-10.remove-all-margins
			= text_field_tag :search, params[:search], placeholder: "Search...", class: "form-control"
		.col-xs-2.remove-all-margins
			= submit_tag "Go", :name => 'nil', class: "btn btn-default"
		.clearfix

app/views/layouts/admin.html.slim
doctype html
html
  head
    title Snippr
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans+Mono|Open+Sans:400,300,700"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", media: "all"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js"
    -# = javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
    = javascript_include_tag "application"
    / javascript:
    /   (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    /   (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    /   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    /   })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    /   ga('create', 'UA-43905365-1', 'snippr.co');
    /   ga('send', 'pageview');
    / javascript:
    /   var _kmk = _kmk || '8731335d908493cd0d58b99229da5ad7965bf38c';
    /   function _kms(u){
    /     setTimeout(function(){
    /       var d = document, f = d.getElementsByTagName('script')[0],
    /       s = d.createElement('script');
    /       s.type = 'text/javascript'; s.async = true; s.src = u;
    /       f.parentNode.insertBefore(s, f);
    /     }, 1);
    /   }
    /   _kms('//i.kissmetrics.com/i.js');
    /   _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
    = csrf_meta_tags
  body
    header.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          a.navbar-brand href="/" Snippr Administration
        .navbar-collapse.collapse
          .navbar-form.navbar-right
    
    .container
      .row
        .col-md-3
          = render :partial => 'layouts/admin/navigation'
        .col-md-9
          = yield

    #footer.text-center
      .container
        p.text-muted.credit by 88Yaks

app/views/layouts/application.html.slim
doctype html
html.common-layout ng-app='snipprapp'
  head
    title Snippr
    meta name="google-site-verification" content="7avZXxlquzOxLkvuUrfgdyx99LSM5E2mtn90d8FXWa4"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans+Mono|Open+Sans:400,300,700"
    link href='http://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css"

    = stylesheet_link_tag "application"
    = javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
    = javascript_include_tag "application"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
    = javascript_tag "AUTH_TOKEN = '#{form_authenticity_token}';" if protect_against_forgery?
    = javascript_tag "USER_TOKEN = '#{current_user.token}';" if user_signed_in?
    = render partial: "layouts/js_tracking_links" if Rails.env.production?
    = favicon_link_tag 'favicon.png'
    = csrf_meta_tags


  body
    .hidden-xs
      nav.navbar.navbar-default.navbar-static-top.nav-defined role="navigation"
        
        .container
          .navbar-header.col-sm-3
            button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand#logo href="/timeline" 

          .collapse.navbar-collapse.navbar-ex1-collapse.navbar-right
            .pull-left role="search"
              = render partial: "layouts/user_search" unless @disable_search_nav
            .pull-right
              = render partial: "layouts/user_account_nav"

    .visible-xs         
      nav.navbar.navbar-default.navbar-fixed-top.nav-defined role="navigation"
        
        .container
          .navbar-header.col-sm-3
            button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
              span.sr-only Toggle navigation
              span.icon-bar
              span.icon-bar
              span.icon-bar
            a.navbar-brand#logo href="/timeline" 


          .collapse.navbar-collapse.navbar-ex1-collapse.navbar-right

            div role="search"
              = render partial: "layouts/user_search" unless @disable_search_nav
            br.clearfix
            .pull-right
              = render partial: "layouts/user_account_nav"
            .clearfix

            .side-nav
              span.title.spaced-at-right
                a.text-info href="/timeline"  HOME  
              span.title.spaced-at-right  | 
              span.title.spaced-at-right
                a.text-info href="/authors"  AUTHORS 
              span.title.spaced-at-right  | 
              span.title
                a.text-info href="/users/readlists"  READLISTS 
              .clearfix
       

    .container
      = render partial: "layouts/alerts"
      br
      br
      = yield


    / #footer.text-center
    /   .container
    /     p.text-muted.credit by 88Yaks
      
    = debug(params) if Rails.env.development?

app/views/layouts/application.landing.html.slim
doctype html
html.landing ng-app=''
  head
    title Snippr
    meta name="google-site-verification" content="7avZXxlquzOxLkvuUrfgdyx99LSM5E2mtn90d8FXWa4"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans+Mono|Open+Sans:400,300,700"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"
    = stylesheet_link_tag "application"
    = javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
    = javascript_include_tag "application"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
    = csrf_meta_tags
  body
    header.navbar.navbar-default.navbar-static-top
      .container
        .navbar-header
          a.navbar-brand href="/" Snippr
        .navbar-collapse.collapse
          .navbar-form.navbar-right
            a.btn.btn-success.scroll href="#new_subscription" Request for Beta
    .container
      = yield

    / #footer.text-center
    /   .container
    /     p.text-muted.credit by 88Yaks

app/views/layouts/signup.html.slim
doctype html
html.signup ng-app=''
  head
    title Snippr
    meta name="google-site-verification" content="7avZXxlquzOxLkvuUrfgdyx99LSM5E2mtn90d8FXWa4"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Droid+Sans+Mono|Open+Sans:400,300,700"
    = stylesheet_link_tag "//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css"
    = stylesheet_link_tag "application"
    = javascript_include_tag "http://code.jquery.com/jquery-1.10.1.min.js"
    = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/angularjs/1.0.8/angular.min.js"
    = javascript_include_tag "application"
    = javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
    meta name="description" content="Read blogs and articles of your favorite writers from all over the web in one place."

    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-43905365-1', 'snippr.co');
      ga('send', 'pageview');
    javascript:
      var _kmk = _kmk || '8731335d908493cd0d58b99229da5ad7965bf38c';
      function _kms(u){
        setTimeout(function(){
          var d = document, f = d.getElementsByTagName('script')[0],
          s = d.createElement('script');
          s.type = 'text/javascript'; s.async = true; s.src = u;
          f.parentNode.insertBefore(s, f);
        }, 1);
      }
      _kms('//i.kissmetrics.com/i.js');
      _kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
    = csrf_meta_tags
  body

    / header.navbar.navbar-default.navbar-static-top
    /   .container
    /     .navbar-header
    /       a.navbar-brand href="/" Snippr
    /     .navbar-collapse.collapse
    /       .navbar-form.navbar-right
    nav.navbar.navbar-default.navbar-static-top.nav-defined role="navigation"
      .container
        .navbar-header
          button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand#logo href="/" 
        .collapse.navbar-collapse.navbar-ex1-collapse
          / ul.nav.navbar-nav
          /   li.active
          /     a href="#" Link
          /   li
          /     a href="#" Link
      
          .navbar-right
            .social-buttons.landing.navbar-left.spaced-at-right
              span.spaced-at-right
                a href="https://www.facebook.com/SnipprCo"
                  i.icon-facebook

              span.spaced-at-right
                a href="https://twitter.com/SnipprCo"
                  i.icon-twitter
              span.spaced-at-right
                a href="http://www.linkedin.com/company/snippr"
                  i.icon-linkedin

       
    div
      = render partial: "layouts/alerts"
      = yield

    / #footer.text-center
    /   .container
    /     p.credit by 88Yaks